id: P004183
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7534
  title: ཉི་ཁྲི། ༼ཤིང་དཔར།༽
  author: ''
  volumes:
    7cc1f48d084f4400ae0f326ced4b299b:
      image_group_id: I3CN7639
      title: ''
      volume_number: 1
      total_pages: 1117
    f46058dfad1342f392a7cbc9feba1f05:
      image_group_id: I3CN7640
      title: ''
      volume_number: 2
      total_pages: 1097
    9e5d06a541934aad8fc5bfd7ab320e87:
      image_group_id: I3CN7641
      title: ''
      volume_number: 3
      total_pages: 1075
