id: I3E2CAAC5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:59:38+00:00'
last_modified: '2022-06-07T20:52:51.984792+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7534
  title: ཉི་ཁྲི། ༼ཤིང་དཔར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DFB6:
      image_group_id: I3CN7639
      title: ''
      total_pages: 1117
      order: 1
      base_file: DFB6.txt
    84FF:
      image_group_id: I3CN7640
      title: ''
      total_pages: 1097
      order: 2
      base_file: 84FF.txt
    D43C:
      image_group_id: I3CN7641
      title: ''
      total_pages: 1075
      order: 3
      base_file: D43C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
